### ISSUE TITLE
wrong function name

### ISSUE THREAD

**Issue by mrchar** [Soluto/casbin-nats-watcher#5]
the function name should be finalizer.

https://github.com/Soluto/casbin-nats-watcher/blob/ea7d2eff687d0b6b62c0ecc04d982685d0798831/watcher.go#L90-L95

**Comment by hsluoyz** [comment]
Hi, is anyone here still maintaining this project?

**Comment by vtolstov** [comment]
If nobody - i can take it, I'm using nats and casbin

**Comment by hsluoyz** [comment]
Hi @vtolstov , I think they are not maintaining it any more. You can create a repo and give me the permission.

**Comment by AleF83** [comment]
Hi guys, I'll fix the function name.

**Comment by vtolstov** [comment]
Thanks!
